n = input('Type anything here:')
print('The primitive type of this value is: {}'.format(type(n)))
print('is it space only? {}'.format(n.isspace()))
print('Is it a number? {}'.format(n.isnumeric()))
print('Is it alphabetic? {}'.format(n.isalpha()))
print('Is it alphanumeric? {}'.format(n.isalnum()))
print('Is it all caps? {}'.format(n.isupper()))
print('Is it all lowercase? {}'.format(n.islower()))
print('Is it capitalized? {}'.format(n.istitle()))
